// Code generated by gonstructor -type ShellSidecar -constructorTypes builder; DO NOT EDIT.

package sidecar

import (
	"github.com/reconquest/snake-runner/internal/spawner"
	"github.com/reconquest/snake-runner/internal/sshkey"
)

type ShellSidecarBuilder struct {
	spawner        spawner.Spawner
	name           string
	slug           string
	promptConsumer spawner.PromptConsumer
	outputConsumer spawner.OutputConsumer
	pipelinesDir   string
	sshKey         sshkey.Key
}

func NewShellSidecarBuilder() *ShellSidecarBuilder {
	return &ShellSidecarBuilder{}
}

func (b *ShellSidecarBuilder) Spawner(spawner spawner.Spawner) *ShellSidecarBuilder {
	b.spawner = spawner
	return b
}

func (b *ShellSidecarBuilder) Name(name string) *ShellSidecarBuilder {
	b.name = name
	return b
}

func (b *ShellSidecarBuilder) Slug(slug string) *ShellSidecarBuilder {
	b.slug = slug
	return b
}

func (b *ShellSidecarBuilder) PromptConsumer(promptConsumer spawner.PromptConsumer) *ShellSidecarBuilder {
	b.promptConsumer = promptConsumer
	return b
}

func (b *ShellSidecarBuilder) OutputConsumer(outputConsumer spawner.OutputConsumer) *ShellSidecarBuilder {
	b.outputConsumer = outputConsumer
	return b
}

func (b *ShellSidecarBuilder) PipelinesDir(pipelinesDir string) *ShellSidecarBuilder {
	b.pipelinesDir = pipelinesDir
	return b
}

func (b *ShellSidecarBuilder) SshKey(sshKey sshkey.Key) *ShellSidecarBuilder {
	b.sshKey = sshKey
	return b
}

func (b *ShellSidecarBuilder) Build() *ShellSidecar {
	return &ShellSidecar{
		spawner:        b.spawner,
		name:           b.name,
		slug:           b.slug,
		promptConsumer: b.promptConsumer,
		outputConsumer: b.outputConsumer,
		pipelinesDir:   b.pipelinesDir,
		sshKey:         b.sshKey,
	}
}
