// Code generated by gonstructor -type Sidecar -constructorTypes builder; DO NOT EDIT.

package sidecar

import "github.com/reconquest/snake-runner/internal/cloud"

type SidecarBuilder struct {
	cloud           *cloud.Cloud
	name            string
	pipelinesDir    string
	slug            string
	commandConsumer cloud.CommandConsumer
	outputConsumer  cloud.OutputConsumer
	sshKey          string
}

func NewSidecarBuilder() *SidecarBuilder {
	return &SidecarBuilder{}
}
func (b *SidecarBuilder) Cloud(cloud *cloud.Cloud) *SidecarBuilder {
	b.cloud = cloud
	return b
}
func (b *SidecarBuilder) Name(name string) *SidecarBuilder {
	b.name = name
	return b
}
func (b *SidecarBuilder) PipelinesDir(pipelinesDir string) *SidecarBuilder {
	b.pipelinesDir = pipelinesDir
	return b
}
func (b *SidecarBuilder) Slug(slug string) *SidecarBuilder {
	b.slug = slug
	return b
}
func (b *SidecarBuilder) CommandConsumer(commandConsumer cloud.CommandConsumer) *SidecarBuilder {
	b.commandConsumer = commandConsumer
	return b
}
func (b *SidecarBuilder) OutputConsumer(outputConsumer cloud.OutputConsumer) *SidecarBuilder {
	b.outputConsumer = outputConsumer
	return b
}
func (b *SidecarBuilder) SshKey(sshKey string) *SidecarBuilder {
	b.sshKey = sshKey
	return b
}
func (b *SidecarBuilder) Build() *Sidecar {
	return &Sidecar{cloud: b.cloud, name: b.name, pipelinesDir: b.pipelinesDir, slug: b.slug, commandConsumer: b.commandConsumer, outputConsumer: b.outputConsumer, sshKey: b.sshKey}
}
