// Code generated by gonstructor -type Process; DO NOT EDIT.

package main

import (
	"context"

	"github.com/reconquest/cog"
)

func NewProcess(runner *Runner, log *cog.Logger, task *Task, cloud *Cloud, container string, ctx context.Context) *Process {
	return &Process{runner: runner, log: log, task: task, cloud: cloud, container: container, ctx: ctx}
}
