// Code generated by gonstructor -type registerRequest; DO NOT EDIT.

package main

func NewRegisterRequest(name string, publicKey string) *registerRequest {
	return &registerRequest{Name: name, PublicKey: publicKey}
}
