// Code generated by gonstructor -type Scheduler; DO NOT EDIT.

package main

func NewScheduler(spots chan struct{}, runner *Runner, cloud *Cloud) *Scheduler {
	return &Scheduler{spots: spots, runner: runner, cloud: cloud}
}
