version: '3'

silent: true

vars:
  pwd:
    sh: pwd
  random_uuid:
    sh: cat /proc/sys/kernel/random/uuid
  token: ""
  major_minor:
    sh: "git describe --tags --abbrev=0"
  patch:
    sh: "git rev-list $(git describe --tags --abbrev=0)..HEAD --count"
  version: "{{.major_minor}}.{{.patch}}"
  commit:
    sh: "git rev-parse --short HEAD"

  container: bitbucket.local
  network:
    sh: "./taskutils/net '{{.container}}'"
  name: ""
  volume: "snake-runner-secrets"

includes:
  go: tasks/go.yml
  docker: tasks/docker.yml

tasks:
  version:
    desc: print version
    cmds:
      - printf "%s" "{{.version}}"

  watch:
    desc: watch for changes
    cmds:
      - ./taskutils/watch

  rr:
    cmds:
      - task: go:build
      - mkdir -p .runners/{{.random_uuid}}
      - SNAKE_NAME={{.random_uuid}}
        SNAKE_MASTER_ADDRESS=https://bitbucket.local/
        SNAKE_ACCESS_TOKEN_PATH=.runners/{{.random_uuid}}/token
        SNAKE_REGISTRATION_TOKEN={{.token}}
        SNAKE_SSH_KEY_PATH=.runners/{{.random_uuid}}/id_rsa
        SNAKE_PIPELINES_DIR=.runners/{{.random_uuid}}/pipelines
        SNAKE_SIDECAR_DOCKER_VOLUMES=['/etc/ssl:/etc/ssl:ro','/etc/ca-certificates:/etc/ca-certificates:ro']
        SNAKE_LOG_TRACE=true
        ./snake-runner -c ./conf/dev.conf

  dock:
    cmds:
      - task: docker:snake-runner:build
      - docker run -it
          -e SNAKE_NAME={{.name}}
          -e SNAKE_MASTER_ADDRESS=http://{{.container}}:7990/
          -e SNAKE_REGISTRATION_TOKEN={{.token}}
          -e SNAKE_LOG_DEBUG=true
          -e SNAKE_LOG_TRACE=true
          -e SNAKE_DOCKER_NETWORK={{.network}}
          -e 'SNAKE_DOCKER_VOLUMES=["/var/run/docker.sock:/var/run/docker.sock"]'
          -v {{.volume}}:/var/lib/snake-runner/secrets
          -v /var/run/docker.sock:/var/run/docker.sock
          --network {{.network}}
          --rm
          reconquest/snake-runner:latest

  licenses:
    glice -gh "{{.GITHUB_TOKEN}}" | taskutils/licenses > LICENSES_THIRD_PARTY
