#!/bin/bash

opt="$1"

tag=$(git describe --tags --abbrev=0)
dots=$(grep -o '\.' <<< "$tag" | wc -l)

major-minor() {
    if [[ $dots == 2 ]]; then
        cut -d. -f1,2 <<< "$tag"
    else
        echo "$tag"
    fi
}

if [[ "$opt" == "major-minor" ]]; then
    major-minor
    exit
fi


if [[ $dots == 2 ]]; then
    patch=$(cut -d. -f3 <<< "$tag")
    if [[ "$patch" =~ beta$ ]]; then
        echo "$tag$(git rev-list $tag..HEAD --count)-$(git rev-parse --short HEAD)"
    else
        echo $tag
    fi
    exit
fi

echo "$(major-minor).$(git rev-list $tag..HEAD --count)"
