version: '3'

vars:
  nproc:
    sh: nproc

tasks:
  generate:
    desc: run go generate
    cmds:
      - find -name '*_gen.go' -delete
      - grep -lr 'go:generate' ./cmd/ ./internal/ | xargs -n1 -I{} -P{{.nproc}} go generate -x {}
      - gofumports -w $(find -name '*_gen.go' -print)
    sources:
      - '**/*.go'
    generates:
      - '**/*_gen.go'
    method: checksum

  build:
    desc: build go code
    deps: [generate]
    cmds:
      - 'echo Building version: {{.version}}-{{.commit}} >&2'
      - go build
          -ldflags="-X=github.com/reconquest/snake-runner/internal/builtin.Version={{.version}}-{{.commit}}"
          ./cmd/snake-runner

  'build:windows':
    desc: build go code with GOOS=windows
    cmds:
      - GOOS=windows task go:build

  'build:docker':
    desc: build go code for docker
    deps: [generate]
    cmds:
      - 'echo Building version: {{.version}}-{{.commit}}-docker >&2'
      - CGO_ENABLED=0 go build
          -o snake-runner.docker
          -ldflags="-X=github.com/reconquest/snake-runner/internal/builtin.Version={{.version}}-{{.commit}}-docker"
          ./cmd/snake-runner
