version: '3'

tasks:
  beta:
    desc: release beta
    cmds:
      - git tag "{{.version}}-{{.commit}}"
      - git push origin "{{.version}}-{{.commit}}"
      - VERSION="{{.version}}-{{.commit}}" goreleaser release --rm-dist
