version: '3'

vars:
  address: https://bitbucket.local
  token: 'not specified'

tasks:
  copy:
    desc: copy to windows vm
    cmds:
      - task go:build:windows
      - sshpass -p XXXxxx1 ssh administrator@172.17.0.128 New-Item -Path C:\\snake-runner\\ -ItemType Directory -Force \| Out-Null
      - echo "% Uploading executable"
      - sshpass -p XXXxxx1 scp snake-runner.exe administrator@172.17.0.128:"C:\\snake-runner\\snake-runner.exe"

  run:
    desc: run runner on windows vm
    cmds:
      - sshpass -p XXXxxx1 ssh administrator@172.17.0.128
          "\$env:SNAKE_MASTER_ADDRESS='{{.address}}';
          \$env:SNAKE_REGISTRATION_TOKEN='{{.token}}';
          C:\\snake-runner\\snake-runner.exe"

  kill:
    desc: run runner on windows vm
    cmds:
      - sshpass -p XXXxxx1 ssh administrator@172.17.0.128 taskkill /f /im snake-runner.exe
