// Code generated by gonstructor --type Masker --init init; DO NOT EDIT.

package masker

import (
	"io"

	"github.com/reconquest/snake-runner/internal/env"
)

func NewMasker(
	env *env.Env,
	secrets []string,
	dst io.WriteCloser,
) *Masker {
	r := &Masker{
		env:     env,
		secrets: secrets,
		dst:     dst,
	}

	r.init()

	return r
}
