// Code generated by gonstructor -type RunnerRegister; DO NOT EDIT.

package requests

func NewRunnerRegister(name string, publicKey string) *RunnerRegister {
	return &RunnerRegister{Name: name, PublicKey: publicKey}
}
