// Code generated by gonstructor -type RunnerRegister; DO NOT EDIT.

package requests

func NewRunnerRegister(name string, token string, publicKey string) *RunnerRegister {
	return &RunnerRegister{Name: name, Token: token, PublicKey: publicKey}
}
