// Code generated by gonstructor -type TaskUpdate; DO NOT EDIT.

package requests

import (
	"time"

	"github.com/reconquest/snake-runner/internal/status"
)

func NewTaskUpdate(
	status status.Status,
	startedAt *time.Time,
	finishedAt *time.Time,
) *TaskUpdate {
	return &TaskUpdate{
		Status:     status,
		StartedAt:  startedAt,
		FinishedAt: finishedAt,
	}
}
