// Code generated by gonstructor -type Task; DO NOT EDIT.

package requests

func NewTask(runningPipelines []int, queryPipeline bool, sSHKey string) *Task {
	return &Task{RunningPipelines: runningPipelines, QueryPipeline: queryPipeline, SSHKey: sSHKey}
}
