// Code generated by gonstructor -type TaskUpdate; DO NOT EDIT.

package requests

import "time"

func NewTaskUpdate(
	status string,
	startedAt *time.Time,
	finishedAt *time.Time,
) *TaskUpdate {
	return &TaskUpdate{
		Status:     status,
		StartedAt:  startedAt,
		FinishedAt: finishedAt,
	}
}
