// Code generated by gonstructor --type=DockerProbe; DO NOT EDIT.

package main

import "github.com/reconquest/snake-runner/internal/executor/docker"

func NewDockerProbe(docker *docker.Docker) *DockerProbe {
	return &DockerProbe{
		docker: docker,
	}
}
