// Code generated by gonstructor -type LogsBufferedWriter -init init; DO NOT EDIT.

package main

import "time"

func NewLogsBufferedWriter(
	size int,
	duration time.Duration,
	flush func(text string),
) *LogsBufferedWriter {
	r := &LogsBufferedWriter{
		size:     size,
		duration: duration,
		flush:    flush,
	}

	r.init()

	return r
}
