// Code generated by gonstructor --type=ProbeFactory; DO NOT EDIT.

package main

import "github.com/reconquest/snake-runner/internal/runner"

func NewProbeFactory(config *runner.Config) *ProbeFactory {
	return &ProbeFactory{
		config: config,
	}
}
