// Code generated by gonstructor -type ProcessJob -init init; DO NOT EDIT.

package main

import (
	"context"

	"github.com/reconquest/cog"
	"github.com/reconquest/snake-runner/internal/cloud"
	"github.com/reconquest/snake-runner/internal/config"
	"github.com/reconquest/snake-runner/internal/snake"
	"github.com/reconquest/snake-runner/internal/tasks"
)

func NewProcessJob(
	ctx context.Context,
	cloud *cloud.Cloud,
	client *Client,
	config config.Pipeline,
	runnerConfig *RunnerConfig,
	task tasks.PipelineRun,
	utilization chan *cloud.Container,
	job snake.PipelineJob,
	log *cog.Logger,
) *ProcessJob {
	r := &ProcessJob{
		ctx:          ctx,
		cloud:        cloud,
		client:       client,
		config:       config,
		runnerConfig: runnerConfig,
		task:         task,
		utilization:  utilization,
		job:          job,
		log:          log,
	}

	r.init()

	return r
}
