// Code generated by gonstructor -type ProcessPipeline; DO NOT EDIT.

package main

import (
	"context"

	"github.com/reconquest/cog"
	"github.com/reconquest/snake-runner/internal/cloud"
	"github.com/reconquest/snake-runner/internal/sshkey"
	"github.com/reconquest/snake-runner/internal/tasks"
)

func NewProcessPipeline(parentCtx context.Context, ctx context.Context, client *Client, runnerConfig *RunnerConfig, task tasks.PipelineRun, cloud *cloud.Cloud, log *cog.Logger, utilization chan *cloud.Container, sshKey sshkey.Key) *ProcessPipeline {
	return &ProcessPipeline{parentCtx: parentCtx, ctx: ctx, client: client, runnerConfig: runnerConfig, task: task, cloud: cloud, log: log, utilization: utilization, sshKey: sshKey}
}
