// Code generated by gonstructor --type=ShellProbe; DO NOT EDIT.

package main

import "github.com/reconquest/snake-runner/internal/executor/shell"

func NewShellProbe(shell *shell.Shell) *ShellProbe {
	return &ShellProbe{
		shell: shell,
	}
}
