// Code generated by gonstructor -type Bufferer -init init; DO NOT EDIT.

package bufferer

import "time"

func NewBufferer(
	chanSize int,
	flushSize int,
	flushInterval time.Duration,
	flush func([]byte),
) *Bufferer {
	r := &Bufferer{
		chanSize:      chanSize,
		flushSize:     flushSize,
		flushInterval: flushInterval,
		flush:         flush,
	}

	r.init()

	return r
}
