// Code generated by gonstructor -type Process; DO NOT EDIT.

package pipeline

import (
	"context"

	"github.com/reconquest/cog"
	"github.com/reconquest/snake-runner/internal/api"
	"github.com/reconquest/snake-runner/internal/runner"
	"github.com/reconquest/snake-runner/internal/spawner"
	"github.com/reconquest/snake-runner/internal/sshkey"
	"github.com/reconquest/snake-runner/internal/tasks"
)

func NewProcess(
	parentCtx context.Context,
	ctx context.Context,
	client *api.Client,
	runnerConfig *runner.Config,
	task tasks.PipelineRun,
	spawner spawner.Spawner,
	log *cog.Logger,
	utilization chan spawner.Container,
	sshKey sshkey.Key,
) *Process {
	return &Process{
		parentCtx:    parentCtx,
		ctx:          ctx,
		client:       client,
		runnerConfig: runnerConfig,
		task:         task,
		spawner:      spawner,
		log:          log,
		utilization:  utilization,
		sshKey:       sshKey,
	}
}
