// Code generated by gonstructor -type Builder; DO NOT EDIT.

package env

import (
	"github.com/reconquest/snake-runner/internal/config"
	"github.com/reconquest/snake-runner/internal/runner"
	"github.com/reconquest/snake-runner/internal/snake"
	"github.com/reconquest/snake-runner/internal/tasks"
)

func NewBuilder(
	task tasks.PipelineRun,
	pipeline snake.Pipeline,
	job snake.PipelineJob,
	config config.Pipeline,
	configJob config.Job,
	runnerConfig *runner.Config,
	gitDir string,
	sshSocketPath string,
	sshKnownHostsPath string,
) *Builder {
	return &Builder{
		task:              task,
		pipeline:          pipeline,
		job:               job,
		config:            config,
		configJob:         configJob,
		runnerConfig:      runnerConfig,
		gitDir:            gitDir,
		sshSocketPath:     sshSocketPath,
		sshKnownHostsPath: sshKnownHostsPath,
	}
}
